import type {
  Claim,
  Customer,
  Driver,
  Invoice,
  Job,
  JobStatus,
  PayrollLine,
  Route,
  Vehicle,
} from "./types";

export const drivers: Driver[] = [
  {
    id: "DRV-1042",
    name: "Marcus Reyes",
    phone: "(305) 555-2031",
    email: "marcus.r@arsemia.co",
    vehicleId: "VEH-204",
    vehicleName: "26' Box Truck #204",
    status: "On Job",
    jobsCompleted: 312,
    revenueHandled: 184250,
    rating: 4.9,
    currentLocation: "Brickell, Miami",
    currentJobId: "JOB-10421",
    eta: "11:42 AM",
    documentsOk: true,
    documentExpiry: "2026-08-12",
    avatarColor: "bg-brand-500",
  },
  {
    id: "DRV-1043",
    name: "Sofia Hernandez",
    phone: "(305) 555-2032",
    email: "sofia.h@arsemia.co",
    vehicleId: "VEH-207",
    vehicleName: "Sprinter Van #207",
    status: "En Route",
    jobsCompleted: 278,
    revenueHandled: 162100,
    rating: 4.8,
    currentLocation: "Coral Gables",
    currentJobId: "JOB-10422",
    eta: "12:05 PM",
    documentsOk: true,
    documentExpiry: "2026-11-04",
    avatarColor: "bg-emerald-500",
  },
  {
    id: "DRV-1044",
    name: "Trevon Walker",
    phone: "(305) 555-2033",
    email: "trevon.w@arsemia.co",
    vehicleId: "VEH-211",
    vehicleName: "20' Box Truck #211",
    status: "Available",
    jobsCompleted: 198,
    revenueHandled: 121800,
    rating: 4.7,
    currentLocation: "Doral Yard",
    documentsOk: true,
    documentExpiry: "2026-04-22",
    avatarColor: "bg-amber-500",
  },
  {
    id: "DRV-1045",
    name: "Anya Volkov",
    phone: "(305) 555-2034",
    email: "anya.v@arsemia.co",
    vehicleId: "VEH-215",
    vehicleName: "Cargo Van #215",
    status: "On Job",
    jobsCompleted: 256,
    revenueHandled: 154300,
    rating: 4.9,
    currentLocation: "Wynwood",
    currentJobId: "JOB-10425",
    eta: "1:15 PM",
    documentsOk: true,
    documentExpiry: "2026-07-30",
    avatarColor: "bg-violet-500",
  },
  {
    id: "DRV-1046",
    name: "Jamal Carter",
    phone: "(305) 555-2035",
    email: "jamal.c@arsemia.co",
    vehicleId: "VEH-220",
    vehicleName: "26' Box Truck #220",
    status: "Break",
    jobsCompleted: 410,
    revenueHandled: 241600,
    rating: 4.95,
    currentLocation: "Coral Gables",
    documentsOk: false,
    documentExpiry: "2026-05-30",
    avatarColor: "bg-rose-500",
  },
  {
    id: "DRV-1047",
    name: "Elena Park",
    phone: "(305) 555-2036",
    email: "elena.p@arsemia.co",
    vehicleId: "VEH-224",
    vehicleName: "Sprinter Van #224",
    status: "Available",
    jobsCompleted: 142,
    revenueHandled: 88200,
    rating: 4.6,
    currentLocation: "Doral",
    documentsOk: true,
    documentExpiry: "2026-09-19",
    avatarColor: "bg-cyan-500",
  },
  {
    id: "DRV-1048",
    name: "Ravi Shankar",
    phone: "(305) 555-2037",
    email: "ravi.s@arsemia.co",
    vehicleId: "VEH-230",
    vehicleName: "Tractor Trailer #230",
    status: "Offline",
    jobsCompleted: 89,
    revenueHandled: 96400,
    rating: 4.4,
    currentLocation: "Fort Lauderdale",
    documentsOk: true,
    documentExpiry: "2027-01-08",
    avatarColor: "bg-fuchsia-500",
  },
];

export const jobs: Job[] = [
  {
    id: "JOB-10421",
    customer: "Whitman Residence",
    customerPhone: "(305) 555-7741",
    pickup: "742 Brickell Ave, Miami, FL",
    delivery: "118 Collins Ave, Miami Beach, FL",
    pickupCity: "Miami",
    deliveryCity: "Miami",
    type: "Local Move",
    cuFt: 640,
    miles: 4.2,
    status: "Pickup Started",
    driverId: "DRV-1042",
    driverName: "Marcus Reyes",
    crew: ["Marcus Reyes", "Diego Soto"],
    price: 2480,
    payrollStatus: "Pending",
    scheduledAt: "2026-05-24T08:00:00",
    eta: "11:42 AM",
    zone: "Downtown Miami",
    priority: "High",
    notes: "Elevator reserved 9-11am. Piano on dolly.",
  },
  {
    id: "JOB-10422",
    customer: "Hayward Logistics",
    customerPhone: "(786) 555-8821",
    pickup: "3201 W 49th St, Hialeah, FL",
    delivery: "1188 Biscayne Blvd, Miami, FL",
    pickupCity: "Hialeah",
    deliveryCity: "Miami",
    type: "Commercial",
    cuFt: 1240,
    miles: 18.6,
    status: "En Route",
    driverId: "DRV-1043",
    driverName: "Sofia Hernandez",
    crew: ["Sofia Hernandez", "Tomas Quill", "Brian Lee"],
    price: 4625,
    payrollStatus: "Pending",
    scheduledAt: "2026-05-24T07:30:00",
    eta: "12:05 PM",
    zone: "Hialeah",
    priority: "High",
  },
  {
    id: "JOB-10423",
    customer: "Avery Chen",
    customerPhone: "(305) 555-9912",
    pickup: "1622 Lincoln Rd, Miami Beach, FL",
    delivery: "Arsemia Storage - Bay A12",
    pickupCity: "Miami",
    deliveryCity: "Miami",
    type: "Storage In",
    cuFt: 285,
    miles: 6.1,
    status: "Assigned",
    driverId: "DRV-1044",
    driverName: "Trevon Walker",
    crew: ["Trevon Walker", "Diego Soto"],
    price: 1180,
    payrollStatus: "Pending",
    scheduledAt: "2026-05-24T10:00:00",
    eta: "10:30 AM",
    zone: "North Miami",
    priority: "Medium",
  },
  {
    id: "JOB-10424",
    customer: "Granite Interiors",
    customerPhone: "(305) 555-3344",
    pickup: "98 NW 2S Miami Ave, Miami, FL",
    delivery: "451 NE 2nd Ave, Miami, FL",
    pickupCity: "Miami",
    deliveryCity: "Miami",
    type: "Delivery",
    cuFt: 210,
    miles: 3.4,
    status: "Unassigned",
    crew: [],
    price: 740,
    payrollStatus: "Pending",
    scheduledAt: "2026-05-24T11:00:00",
    zone: "Wynwood",
    priority: "Medium",
  },
  {
    id: "JOB-10425",
    customer: "Lindsey & Roe LLP",
    customerPhone: "(305) 555-4421",
    pickup: "55 S Miami Ave, Miami, FL",
    delivery: "2 Brickell City Centre, Miami, FL",
    pickupCity: "Miami",
    deliveryCity: "Miami",
    type: "Commercial",
    cuFt: 980,
    miles: 2.8,
    status: "Delivery Started",
    driverId: "DRV-1045",
    driverName: "Anya Volkov",
    crew: ["Anya Volkov", "Brian Lee", "Tomas Quill"],
    price: 3210,
    payrollStatus: "Pending",
    scheduledAt: "2026-05-24T07:00:00",
    eta: "1:15 PM",
    zone: "Brickell",
    priority: "High",
  },
  {
    id: "JOB-10426",
    customer: "Pham Family",
    customerPhone: "(408) 555-7711",
    pickup: "212 Coral Way, Miami, CA",
    delivery: "920 Bayshore Blvd, Tampa, FL",
    pickupCity: "Miami",
    deliveryCity: "Tampa",
    type: "Long Distance",
    cuFt: 1820,
    miles: 386,
    status: "Assigned",
    driverId: "DRV-1048",
    driverName: "Ravi Shankar",
    crew: ["Ravi Shankar", "Marcus Reyes"],
    price: 9840,
    payrollStatus: "Pending",
    scheduledAt: "2026-05-25T06:00:00",
    zone: "Long Distance",
    priority: "High",
    notes: "Two-day move. Hotel pre-booked.",
  },
  {
    id: "JOB-10427",
    customer: "Birch & Co Studio",
    customerPhone: "(305) 555-1180",
    pickup: "Arsemia Storage - Bay C04",
    delivery: "775 NW 27th Ave, Miami, FL",
    pickupCity: "Miami",
    deliveryCity: "Miami",
    type: "Storage Out",
    cuFt: 460,
    miles: 5.5,
    status: "Pickup Completed",
    driverId: "DRV-1042",
    driverName: "Marcus Reyes",
    crew: ["Marcus Reyes"],
    price: 1320,
    payrollStatus: "Approved",
    scheduledAt: "2026-05-24T09:30:00",
    eta: "11:10 AM",
    zone: "Downtown Miami",
    priority: "Medium",
  },
  {
    id: "JOB-10428",
    customer: "Hollins Move",
    customerPhone: "(305) 555-9920",
    pickup: "16 Buena Vista Ave, Miami, FL",
    delivery: "402 Country Club Dr, Aventura, FL",
    pickupCity: "Miami",
    deliveryCity: "Aventura",
    type: "Local Move",
    cuFt: 720,
    miles: 22.4,
    status: "Completed",
    driverId: "DRV-1046",
    driverName: "Jamal Carter",
    crew: ["Jamal Carter", "Diego Soto"],
    price: 2980,
    payrollStatus: "Approved",
    scheduledAt: "2026-05-23T08:00:00",
    zone: "Aventura",
    priority: "Medium",
  },
  {
    id: "JOB-10429",
    customer: "Quinn Estates",
    customerPhone: "(925) 555-7012",
    pickup: "880 NW 24th St, Wynwood, FL",
    delivery: "44 Bayshore Dr, Coconut Grove, FL",
    pickupCity: "Wynwood",
    deliveryCity: "Coconut Grove",
    type: "Local Move",
    cuFt: 175,
    miles: 32.1,
    status: "Cancelled",
    crew: [],
    price: 1480,
    payrollStatus: "Pending",
    scheduledAt: "2026-05-23T13:00:00",
    zone: "Long Distance",
    priority: "Low",
    notes: "Customer cancelled - rebooked for next week.",
  },
  {
    id: "JOB-10430",
    customer: "Atelier West Inc",
    customerPhone: "(305) 555-6610",
    pickup: "2244 Calle 8, Miami, FL",
    delivery: "180 S Dixie Hwy, Pinecrest, FL",
    pickupCity: "Miami",
    deliveryCity: "Pinecrest",
    type: "Commercial",
    cuFt: 1490,
    miles: 19.2,
    status: "Unassigned",
    crew: [],
    price: 5240,
    payrollStatus: "Pending",
    scheduledAt: "2026-05-24T14:00:00",
    zone: "South Dade",
    priority: "High",
  },
  {
    id: "JOB-10431",
    customer: "Renault Family",
    customerPhone: "(650) 555-2210",
    pickup: "300 Brickell Ave, Brickell, FL",
    delivery: "120 Crandon Blvd, Key Biscayne, FL",
    pickupCity: "Brickell",
    deliveryCity: "Key Biscayne",
    type: "Pickup",
    cuFt: 95,
    miles: 9.4,
    status: "Completed",
    driverId: "DRV-1047",
    driverName: "Elena Park",
    crew: ["Elena Park"],
    price: 540,
    payrollStatus: "Paid",
    scheduledAt: "2026-05-22T09:00:00",
    zone: "South Dade",
    priority: "Low",
  },
  {
    id: "JOB-10432",
    customer: "Northstar Foods",
    customerPhone: "(305) 555-1102",
    pickup: "1411 S Miami Ave, Miami, FL",
    delivery: "788 NW 27th Ave, Miami, FL",
    pickupCity: "Miami",
    deliveryCity: "Miami",
    type: "Delivery",
    cuFt: 140,
    miles: 2.1,
    status: "Completed",
    driverId: "DRV-1043",
    driverName: "Sofia Hernandez",
    crew: ["Sofia Hernandez"],
    price: 410,
    payrollStatus: "Paid",
    scheduledAt: "2026-05-23T07:30:00",
    zone: "Wynwood",
    priority: "Low",
  },
];

export const customers: Customer[] = [
  {
    id: "CUS-401",
    name: "Whitman Residence",
    email: "ej.whitman@gmail.com",
    phone: "(305) 555-7741",
    totalJobs: 4,
    lifetimeValue: 11420,
    lastJobDate: "2026-05-24",
    segment: "Residential",
    status: "Active",
  },
  {
    id: "CUS-402",
    name: "Hayward Logistics",
    email: "ops@haywardlogistics.com",
    phone: "(786) 555-8821",
    totalJobs: 22,
    lifetimeValue: 184800,
    lastJobDate: "2026-05-24",
    segment: "Commercial",
    status: "Active",
  },
  {
    id: "CUS-403",
    name: "Avery Chen",
    email: "avery.chen@hey.com",
    phone: "(305) 555-9912",
    totalJobs: 2,
    lifetimeValue: 2640,
    lastJobDate: "2026-05-24",
    segment: "Residential",
    status: "Active",
  },
  {
    id: "CUS-404",
    name: "Lindsey & Roe LLP",
    email: "ap@lindseyroe.com",
    phone: "(305) 555-4421",
    totalJobs: 11,
    lifetimeValue: 64300,
    lastJobDate: "2026-05-24",
    segment: "Commercial",
    status: "Active",
  },
  {
    id: "CUS-405",
    name: "Pham Family",
    email: "lin.pham@icloud.com",
    phone: "(408) 555-7711",
    totalJobs: 1,
    lifetimeValue: 9840,
    lastJobDate: "2026-05-25",
    segment: "Residential",
    status: "Active",
  },
  {
    id: "CUS-406",
    name: "Birch & Co Studio",
    email: "studio@birchco.design",
    phone: "(305) 555-1180",
    totalJobs: 7,
    lifetimeValue: 18420,
    lastJobDate: "2026-05-24",
    segment: "Repeat",
    status: "Active",
  },
  {
    id: "CUS-407",
    name: "Atelier West Inc",
    email: "hello@atelierwest.co",
    phone: "(305) 555-6610",
    totalJobs: 14,
    lifetimeValue: 96200,
    lastJobDate: "2026-05-24",
    segment: "Commercial",
    status: "Active",
  },
  {
    id: "CUS-408",
    name: "Quinn Estates",
    email: "office@quinnestates.com",
    phone: "(925) 555-7012",
    totalJobs: 3,
    lifetimeValue: 4250,
    lastJobDate: "2026-05-23",
    segment: "Residential",
    status: "Lead",
  },
];

export const invoices: Invoice[] = [
  {
    id: "INV-22041",
    jobId: "JOB-10428",
    customer: "Hollins Move",
    issueDate: "2026-05-23",
    dueDate: "2026-06-06",
    amount: 2980,
    status: "Sent",
  },
  {
    id: "INV-22042",
    jobId: "JOB-10432",
    customer: "Northstar Foods",
    issueDate: "2026-05-23",
    dueDate: "2026-06-06",
    amount: 410,
    status: "Paid",
  },
  {
    id: "INV-22043",
    jobId: "JOB-10431",
    customer: "Renault Family",
    issueDate: "2026-05-22",
    dueDate: "2026-06-05",
    amount: 540,
    status: "Paid",
  },
  {
    id: "INV-22044",
    jobId: "JOB-10421",
    customer: "Whitman Residence",
    issueDate: "2026-05-24",
    dueDate: "2026-06-07",
    amount: 2480,
    status: "Draft",
  },
  {
    id: "INV-22045",
    jobId: "JOB-10417",
    customer: "Atelier West Inc",
    issueDate: "2026-04-30",
    dueDate: "2026-05-14",
    amount: 5240,
    status: "Overdue",
  },
];

export const payrollLines: PayrollLine[] = [
  {
    jobId: "JOB-10428",
    customer: "Hollins Move",
    cuFt: 720,
    miles: 22.4,
    cuFtCharge: 2160,
    mileageCharge: 67.2,
    mileageRate: 3,
    extras: 180,
    adminSurcharge: 95,
    tolls: 8,
    commissionableTotal: 2407.2,
    crewPercent: 22,
    foremanPayout: 318.95,
    helperPayout: 210.63,
    deductions: 0,
    finalPayout: 529.58,
    auditFlags: [],
    status: "Approved",
  },
  {
    jobId: "JOB-10427",
    customer: "Birch & Co Studio",
    cuFt: 460,
    miles: 5.5,
    cuFtCharge: 1150,
    mileageCharge: 16.5,
    mileageRate: 3,
    extras: 80,
    adminSurcharge: 75,
    tolls: 0,
    commissionableTotal: 1246.5,
    crewPercent: 20,
    foremanPayout: 249.3,
    helperPayout: 0,
    deductions: 0,
    finalPayout: 249.3,
    auditFlags: [],
    status: "Approved",
  },
  {
    jobId: "JOB-10425",
    customer: "Lindsey & Roe LLP",
    cuFt: 980,
    miles: 2.8,
    cuFtCharge: 2940,
    mileageCharge: 8.4,
    mileageRate: 3,
    extras: 220,
    adminSurcharge: 110,
    tolls: 4.5,
    commissionableTotal: 3168.4,
    crewPercent: 24,
    foremanPayout: 456.25,
    helperPayout: 304.16,
    deductions: 0,
    finalPayout: 760.41,
    auditFlags: [],
    status: "Pending",
  },
  {
    jobId: "JOB-10421",
    customer: "Whitman Residence",
    cuFt: 640,
    miles: 4.2,
    cuFtCharge: 1920,
    mileageCharge: 12.6,
    mileageRate: 3,
    extras: 240,
    adminSurcharge: 95,
    tolls: 0,
    commissionableTotal: 2172.6,
    crewPercent: 22,
    foremanPayout: 286.78,
    helperPayout: 191.19,
    deductions: 0,
    finalPayout: 477.97,
    auditFlags: ["Piano surcharge missing"],
    status: "Flagged",
  },
  {
    jobId: "JOB-10426",
    customer: "Pham Family",
    cuFt: 1820,
    miles: 386,
    cuFtCharge: 5460,
    mileageCharge: 1544,
    mileageRate: 4,
    extras: 380,
    adminSurcharge: 240,
    tolls: 36,
    commissionableTotal: 7384,
    crewPercent: 24,
    foremanPayout: 1063.3,
    helperPayout: 708.86,
    deductions: 0,
    finalPayout: 1772.16,
    auditFlags: [],
    status: "Pending",
  },
  {
    jobId: "JOB-10422",
    customer: "Hayward Logistics",
    cuFt: 1240,
    miles: 18.6,
    cuFtCharge: 3720,
    mileageCharge: 55.8,
    mileageRate: 3,
    extras: 410,
    adminSurcharge: 180,
    tolls: 12,
    commissionableTotal: 4185.8,
    crewPercent: 24,
    foremanPayout: 602.76,
    helperPayout: 401.84,
    deductions: 0,
    finalPayout: 1004.6,
    auditFlags: ["Three-helper crew but rate at 24% - review"],
    status: "Flagged",
  },
  {
    jobId: "JOB-10423",
    customer: "Avery Chen (Storage In)",
    cuFt: 185,
    miles: 6.1,
    cuFtCharge: 600,
    mileageCharge: 18.3,
    mileageRate: 3,
    extras: 0,
    adminSurcharge: 65,
    tolls: 0,
    commissionableTotal: 618.3,
    crewPercent: 20,
    foremanPayout: 123.66,
    helperPayout: 0,
    deductions: 0,
    finalPayout: 123.66,
    auditFlags: ["Billed CuFt below 200 minimum - check billing volume"],
    status: "Flagged",
  },
];

export const claims: Claim[] = [
  {
    id: "CLM-882",
    jobId: "JOB-10421",
    customer: "Whitman Residence",
    damageType: "Furniture Damage",
    status: "Under Review",
    evidenceCount: 6,
    assignedManager: "Lena Brooks",
    amountAtRisk: 1850,
    notes: "Dining table corner scuffed during loading.",
    openedAt: "2026-05-24",
  },
  {
    id: "CLM-881",
    jobId: "JOB-10422",
    customer: "Hayward Logistics",
    damageType: "Late Delivery",
    status: "Customer Contacted",
    evidenceCount: 3,
    assignedManager: "Lena Brooks",
    amountAtRisk: 950,
    notes: "Window service missed by 38 min. Service credit offered.",
    openedAt: "2026-05-23",
  },
  {
    id: "CLM-880",
    jobId: "JOB-10417",
    customer: "Atelier West Inc",
    damageType: "Property Damage",
    status: "New",
    evidenceCount: 2,
    assignedManager: "Owen Marsh",
    amountAtRisk: 4200,
    notes: "Lobby wall scuffed - awaiting building manager photos.",
    openedAt: "2026-05-22",
  },
  {
    id: "CLM-879",
    jobId: "JOB-10408",
    customer: "Pacific Heights Estate",
    damageType: "Lost Item",
    status: "Approved",
    evidenceCount: 4,
    assignedManager: "Lena Brooks",
    amountAtRisk: 620,
    notes: "Single dish box reported missing. Settled with customer.",
    openedAt: "2026-05-18",
  },
  {
    id: "CLM-878",
    jobId: "JOB-10395",
    customer: "Marina Tower 12B",
    damageType: "Billing Dispute",
    status: "Denied",
    evidenceCount: 5,
    assignedManager: "Owen Marsh",
    amountAtRisk: 380,
    notes: "Customer disputed CuFt - inventory list validated.",
    openedAt: "2026-05-14",
  },
];

export const vehicles: Vehicle[] = [
  {
    id: "VEH-204",
    name: "26' Box Truck #204",
    type: "Box Truck",
    vin: "1FDXF46S7XEA00204",
    plate: "ARS-204",
    status: "Active",
    mileage: 84210,
    nextMaintenance: "2026-06-12",
    registrationExpiry: "2027-01-30",
    insuranceExpiry: "2026-12-04",
    currentDriver: "Marcus Reyes",
    gpsActive: true,
    location: "Brickell, Miami",
  },
  {
    id: "VEH-207",
    name: "Sprinter Van #207",
    type: "Sprinter Van",
    vin: "WD3PE7CD8KP000207",
    plate: "ARS-207",
    status: "Active",
    mileage: 52940,
    nextMaintenance: "2026-07-02",
    registrationExpiry: "2026-09-12",
    insuranceExpiry: "2026-12-04",
    currentDriver: "Sofia Hernandez",
    gpsActive: true,
    location: "I-80 W",
  },
  {
    id: "VEH-211",
    name: "20' Box Truck #211",
    type: "Box Truck",
    vin: "1FDXF46S7XEA00211",
    plate: "ARS-211",
    status: "Idle",
    mileage: 102450,
    nextMaintenance: "2026-05-30",
    registrationExpiry: "2026-08-21",
    insuranceExpiry: "2026-12-04",
    currentDriver: "Trevon Walker",
    gpsActive: true,
    location: "Doral Yard",
  },
  {
    id: "VEH-215",
    name: "Cargo Van #215",
    type: "Cargo Van",
    vin: "1FTBR1Y82MKA00215",
    plate: "ARS-215",
    status: "Active",
    mileage: 41880,
    nextMaintenance: "2026-08-09",
    registrationExpiry: "2027-02-04",
    insuranceExpiry: "2026-12-04",
    currentDriver: "Anya Volkov",
    gpsActive: true,
    location: "Wynwood",
  },
  {
    id: "VEH-220",
    name: "26' Box Truck #220",
    type: "Box Truck",
    vin: "1FDXF46S7XEA00220",
    plate: "ARS-220",
    status: "Maintenance",
    mileage: 138210,
    nextMaintenance: "2026-05-25",
    registrationExpiry: "2026-11-12",
    insuranceExpiry: "2026-12-04",
    currentDriver: "Jamal Carter",
    gpsActive: false,
    location: "Service Bay 2",
  },
  {
    id: "VEH-224",
    name: "Sprinter Van #224",
    type: "Sprinter Van",
    vin: "WD3PE7CD8KP000224",
    plate: "ARS-224",
    status: "Active",
    mileage: 38420,
    nextMaintenance: "2026-08-22",
    registrationExpiry: "2027-04-11",
    insuranceExpiry: "2026-12-04",
    currentDriver: "Elena Park",
    gpsActive: true,
    location: "Doral",
  },
  {
    id: "VEH-230",
    name: "Tractor Trailer #230",
    type: "Tractor Trailer",
    vin: "1XPWD49X1ED230",
    plate: "ARS-230",
    status: "Out of Service",
    mileage: 421100,
    nextMaintenance: "2026-06-01",
    registrationExpiry: "2026-10-05",
    insuranceExpiry: "2026-12-04",
    currentDriver: "Ravi Shankar",
    gpsActive: false,
    location: "Doral Yard",
  },
];

export const routes: Route[] = [
  {
    id: "RT-771",
    name: "Downtown Miami Loop",
    driverId: "DRV-1042",
    driverName: "Marcus Reyes",
    stops: 4,
    miles: 18.4,
    durationHours: 6.5,
    zone: "Downtown Miami",
    status: "Active",
    date: "2026-05-24",
  },
  {
    id: "RT-772",
    name: "Hialeah Commercial",
    driverId: "DRV-1043",
    driverName: "Sofia Hernandez",
    stops: 3,
    miles: 42.1,
    durationHours: 5.2,
    zone: "Hialeah",
    status: "Active",
    date: "2026-05-24",
  },
  {
    id: "RT-773",
    name: "Brickell Delivery Sweep",
    driverId: "DRV-1045",
    driverName: "Anya Volkov",
    stops: 6,
    miles: 12.6,
    durationHours: 4.8,
    zone: "Brickell",
    status: "Active",
    date: "2026-05-24",
  },
  {
    id: "RT-774",
    name: "South Dade Pickup Sweep",
    driverId: "DRV-1047",
    driverName: "Elena Park",
    stops: 5,
    miles: 38.4,
    durationHours: 6.0,
    zone: "South Dade",
    status: "Planned",
    date: "2026-05-25",
  },
  {
    id: "RT-775",
    name: "Long-Haul SJ → LA",
    driverId: "DRV-1048",
    driverName: "Ravi Shankar",
    stops: 1,
    miles: 386,
    durationHours: 14,
    zone: "Long Distance",
    status: "Planned",
    date: "2026-05-25",
  },
];

export const revenueByDay = [
  { day: "Mon", revenue: 18420, jobs: 14 },
  { day: "Tue", revenue: 22610, jobs: 17 },
  { day: "Wed", revenue: 19820, jobs: 15 },
  { day: "Thu", revenue: 26490, jobs: 19 },
  { day: "Fri", revenue: 31240, jobs: 22 },
  { day: "Sat", revenue: 28110, jobs: 21 },
  { day: "Sun", revenue: 14860, jobs: 11 },
];

export const revenueByMonth = [
  { month: "Dec", revenue: 412000, payroll: 138000 },
  { month: "Jan", revenue: 438000, payroll: 145000 },
  { month: "Feb", revenue: 462000, payroll: 154000 },
  { month: "Mar", revenue: 488000, payroll: 162000 },
  { month: "Apr", revenue: 516000, payroll: 168000 },
  { month: "May", revenue: 542000, payroll: 178000 },
];

export const jobsByStatus: { status: JobStatus; count: number }[] = [
  { status: "Unassigned", count: 6 },
  { status: "Assigned", count: 9 },
  { status: "En Route", count: 5 },
  { status: "Pickup Started", count: 3 },
  { status: "Pickup Completed", count: 4 },
  { status: "Delivery Started", count: 2 },
  { status: "Completed", count: 12 },
  { status: "Cancelled", count: 1 },
];

export const jobsByZone = [
  { zone: "Downtown Miami", value: 12 },
  { zone: "Hialeah", value: 8 },
  { zone: "South Dade", value: 6 },
  { zone: "Aventura", value: 4 },
  { zone: "Long Distance", value: 3 },
];

export const driverActivity = [
  { hour: "6a", active: 2 },
  { hour: "7a", active: 4 },
  { hour: "8a", active: 6 },
  { hour: "9a", active: 7 },
  { hour: "10a", active: 7 },
  { hour: "11a", active: 6 },
  { hour: "12p", active: 5 },
  { hour: "1p", active: 6 },
  { hour: "2p", active: 7 },
  { hour: "3p", active: 6 },
  { hour: "4p", active: 4 },
  { hour: "5p", active: 3 },
];

export const kpiSnapshot = {
  jobsToday: 26,
  jobsTodayDelta: 12,
  activeDrivers: 7,
  activeDriversDelta: 2,
  pendingDeliveries: 14,
  pendingDeliveriesDelta: -3,
  revenueToday: 31240,
  revenueTodayDelta: 18.4,
  payrollDue: 18840,
  payrollDueDelta: -4.2,
  openClaims: 4,
  openClaimsDelta: 1,
};

export const zones = [
  "Downtown Miami",
  "Wynwood",
  "Brickell",
  "North Miami",
  "Hialeah",
  "Aventura",
  "South Dade",
  "Long Distance",
];

export const jobStatuses: JobStatus[] = [
  "Unassigned",
  "Assigned",
  "En Route",
  "Pickup Started",
  "Pickup Completed",
  "Delivery Started",
  "Completed",
  "Cancelled",
];
