/**
 * Moving Calculator catalog — ported from PoC Calculator v6.
 * Customer-facing and internal payroll rates are kept separate.
 */

export interface PresetItem {
  name: string;
  cuft: number;
}

export interface HandlingItem {
  id: string;
  cat: "dis_reas" | "cardboard" | "floor" | "special" | "lta";
  name: string;
  price: number;
  reassembly?: boolean;
  editable?: boolean;
}

export interface RateConfig {
  cuftRateCustomer: number;
  cuftRateInternal: number;
  milesShortRate: number;
  milesLongRate: number;
  milesThreshold: number;
  cuftMinimum: number;
}

export const DEFAULT_RATES: RateConfig = {
  cuftRateCustomer: 1.5,
  cuftRateInternal: 1.25,
  milesShortRate: 3,
  milesLongRate: 4,
  milesThreshold: 300,
  cuftMinimum: 200,
};

export const PACK_PRICES_CUSTOMER: Record<string, number> = {
  "Box (small)": 16,
  "Box (medium)": 16,
  "Box (large)": 16,
  "Box (extra large)": 20,
  "Dish Pack Box": 20,
  "Wardrobe Box": 30,
  'TV Box (43"-65")': 40,
  'TV Box (66"+)': 60,
  TV: 40,
};

export const PACK_PRICES_INTERNAL: Record<string, number> = {
  "Box (small)": 12,
  "Box (medium)": 12,
  "Box (large)": 12,
  "Box (extra large)": 15,
  "Dish Pack Box": 15,
  "Wardrobe Box": 25,
  'TV Box (43"-65")': 30,
  'TV Box (66"+)': 50,
  TV: 30,
};

export const PRESET_ITEMS: PresetItem[] = [
  { name: "Accent Chair", cuft: 12 },
  { name: "Arm Chair", cuft: 15 },
  { name: "Bar Stool", cuft: 4 },
  { name: "Dining Chair", cuft: 6 },
  { name: "Folding Chair", cuft: 3 },
  { name: "Gaming Chair", cuft: 14 },
  { name: "Lounge Chair", cuft: 18 },
  { name: "Ottoman", cuft: 10 },
  { name: "Papasan Chair", cuft: 16 },
  { name: "Pouf", cuft: 6 },
  { name: "Recliner Chair", cuft: 20 },
  { name: "Rocking Chair", cuft: 14 },
  { name: "Storage Ottoman", cuft: 12 },
  { name: "Love Seat", cuft: 20 },
  { name: "Sectional Sofa (L-shape)", cuft: 90 },
  { name: "Sectional Sofa (U-shape)", cuft: 120 },
  { name: "Sleeper Sofa / Sofa Bed", cuft: 60 },
  { name: "Sofa (2-seater)", cuft: 35 },
  { name: "Sofa (3-seater)", cuft: 50 },
  { name: "Sofa (4-seater)", cuft: 65 },
  { name: "Sofa Recliner (3-seat)", cuft: 55 },
  { name: "Futon", cuft: 30 },
  { name: "Bench (indoor)", cuft: 10 },
  { name: "Coffee Table", cuft: 12 },
  { name: "Console Table", cuft: 15 },
  { name: "Dining Bench", cuft: 12 },
  { name: "Dining Table (extendable)", cuft: 35 },
  { name: "Dining Table (large)", cuft: 30 },
  { name: "Dining Table (small)", cuft: 20 },
  { name: "End Table", cuft: 6 },
  { name: "Entryway Table", cuft: 12 },
  { name: "Folding Table", cuft: 8 },
  { name: "Kitchen Table", cuft: 18 },
  { name: "Patio Table", cuft: 25 },
  { name: "Side Table", cuft: 10 },
  { name: "Adjustable Bed", cuft: 85 },
  { name: "Bunk Bed", cuft: 50 },
  { name: "Cal King Bed Frame", cuft: 30 },
  { name: "Cal King Mattress", cuft: 42 },
  { name: "Crib", cuft: 18 },
  { name: "Day Bed", cuft: 30 },
  { name: "Full Bed Frame", cuft: 20 },
  { name: "Full Mattress", cuft: 25 },
  { name: "Headboard (queen/king)", cuft: 12 },
  { name: "King Bed Frame", cuft: 30 },
  { name: "King Mattress", cuft: 40 },
  { name: "Loft Bed", cuft: 45 },
  { name: "Queen Bed Frame", cuft: 25 },
  { name: "Queen Mattress", cuft: 30 },
  { name: "Storage Bed", cuft: 85 },
  { name: "Toddler Bed", cuft: 18 },
  { name: "Trundle Bed", cuft: 25 },
  { name: "Twin Bed Frame", cuft: 15 },
  { name: "Twin Mattress", cuft: 20 },
  { name: "Armoire", cuft: 25 },
  { name: "Chest of Drawers", cuft: 30 },
  { name: "Dresser (single)", cuft: 25 },
  { name: "Dresser (double)", cuft: 35 },
  { name: "Dresser (triple)", cuft: 45 },
  { name: "Dresser (fully mirrored)", cuft: 40 },
  { name: "Tallboy / Highboy", cuft: 28 },
  { name: "Vanity", cuft: 15 },
  { name: "Bookshelf (small)", cuft: 6 },
  { name: "Bookshelf (medium)", cuft: 12 },
  { name: "Bookshelf (large)", cuft: 20 },
  { name: "Bookshelf (extra large)", cuft: 30 },
  { name: "Buffet / Sideboard", cuft: 30 },
  { name: "China Cabinet (1-2 piece)", cuft: 35 },
  { name: "China Cabinet (3+ piece)", cuft: 50 },
  { name: "Credenza", cuft: 30 },
  { name: "Curio Cabinet", cuft: 22 },
  { name: "Display Cabinet", cuft: 30 },
  { name: "Entertainment Center", cuft: 45 },
  { name: "Wall Unit", cuft: 50 },
  { name: "Media Console", cuft: 18 },
  { name: "TV Stand (small)", cuft: 10 },
  { name: "TV Stand (large)", cuft: 20 },
  { name: "Computer Monitor", cuft: 10 },
  { name: "Computer Tower", cuft: 5 },
  { name: "Desk (small)", cuft: 15 },
  { name: "Desk", cuft: 25 },
  { name: "Desk (large)", cuft: 35 },
  { name: "Desk (L-shape)", cuft: 45 },
  { name: "Desk Chair", cuft: 10 },
  { name: "Filing Cabinet (2-drawer)", cuft: 8 },
  { name: "Filing Cabinet (4-drawer)", cuft: 12 },
  { name: "Office Bookshelf", cuft: 15 },
  { name: "Printer", cuft: 10 },
  { name: "Standing Desk", cuft: 30 },
  { name: "Whiteboard / Corkboard", cuft: 8 },
  { name: "Air Conditioner (portable)", cuft: 12 },
  { name: "Air Conditioner (window)", cuft: 8 },
  { name: "Air Purifier", cuft: 6 },
  { name: "Dehumidifier", cuft: 8 },
  { name: "Dishwasher", cuft: 25 },
  { name: "Dryer", cuft: 30 },
  { name: "Microwave", cuft: 5 },
  { name: "Mini Fridge", cuft: 15 },
  { name: "Refrigerator (standard)", cuft: 40 },
  { name: "Refrigerator (French door)", cuft: 50 },
  { name: "Stove", cuft: 20 },
  { name: "Vacuum Cleaner", cuft: 4 },
  { name: "Washer", cuft: 30 },
  { name: "Wine Fridge (3ft+)", cuft: 12 },
  { name: "Bar Cart", cuft: 12 },
  { name: "Kitchen Cart", cuft: 15 },
  { name: "Kitchen Island", cuft: 25 },
  { name: "Wine Rack", cuft: 8 },
  { name: "Box (small)", cuft: 1.5 },
  { name: "Box (medium)", cuft: 3 },
  { name: "Box (large)", cuft: 7 },
  { name: "Box (extra large)", cuft: 10 },
  { name: "Duffel Bag", cuft: 3 },
  { name: "Suitcase (carry-on)", cuft: 3 },
  { name: "Suitcase (large)", cuft: 7 },
  { name: "Trunk / Hope Chest", cuft: 20 },
  { name: "Wardrobe Box", cuft: 15 },
  { name: "TV", cuft: 20 },
  { name: 'TV Box (43"-65")', cuft: 50 },
  { name: 'TV Box (66"+)', cuft: 80 },
  { name: "Artwork (large, crated)", cuft: 10 },
  { name: "Mirror (small)", cuft: 5 },
  { name: "Mirror (medium)", cuft: 10 },
  { name: "Mirror (large)", cuft: 15 },
  { name: "Mirror XL (6ft+)", cuft: 20 },
  { name: "Picture Frame XL (6ft+)", cuft: 15 },
  { name: "Coat Rack", cuft: 5 },
  { name: "Lamp (floor)", cuft: 8 },
  { name: "Lamp (table)", cuft: 3 },
  { name: "Nightstand", cuft: 5 },
  { name: "Plant (small)", cuft: 5 },
  { name: "Plant (large)", cuft: 20 },
  { name: "Rug (small)", cuft: 5 },
  { name: "Rug", cuft: 15 },
  { name: "Rug (large)", cuft: 25 },
  { name: "Shoe Rack", cuft: 6 },
  { name: "BBQ Grill (small)", cuft: 12 },
  { name: "BBQ Grill", cuft: 25 },
  { name: "Bicycle (kids)", cuft: 6 },
  { name: "Bicycle", cuft: 12 },
  { name: "Kayak / Paddleboard", cuft: 40 },
  { name: "Lawn Mower", cuft: 25 },
  { name: "Patio Chair", cuft: 8 },
  { name: "Scooter", cuft: 20 },
  { name: "Ski Set", cuft: 15 },
  { name: "Snow Blower", cuft: 40 },
  { name: "Surfboard", cuft: 18 },
  { name: "Tool Chest", cuft: 25 },
  { name: "Workbench", cuft: 30 },
  { name: "Aquarium (small)", cuft: 8 },
  { name: "Aquarium (large)", cuft: 25 },
  { name: "Elliptical Machine", cuft: 30 },
  { name: "Exercise Bike", cuft: 15 },
  { name: "Foosball Table", cuft: 25 },
  { name: "Grandfather Clock", cuft: 25 },
  { name: "Gun Safe (large)", cuft: 45 },
  { name: "Motorcycle", cuft: 80 },
  { name: "Peloton Bike", cuft: 25 },
  { name: "Piano (upright)", cuft: 80 },
  { name: "Piano (baby grand)", cuft: 120 },
  { name: "Piano (grand)", cuft: 160 },
  { name: "Ping Pong Table", cuft: 30 },
  { name: "Pool Table", cuft: 80 },
  { name: "Safe (small)", cuft: 10 },
  { name: "Safe", cuft: 25 },
  { name: "Treadmill", cuft: 35 },
  { name: "Weight Bench", cuft: 20 },
];

export const HANDLING_ITEMS: HandlingItem[] = [
  { id: "h01", cat: "dis_reas", name: "Armoire 2-door (wooden)", price: 100, reassembly: true },
  { id: "h02", cat: "dis_reas", name: "Armoire 2-door (glass)", price: 150, reassembly: true },
  { id: "h03", cat: "dis_reas", name: "Armoire 3-door (wooden)", price: 200 },
  { id: "h04", cat: "dis_reas", name: "Armoire 3-door (glass)", price: 250 },
  { id: "h05", cat: "dis_reas", name: "Bookcase tall & wide", price: 100, reassembly: true },
  { id: "h06", cat: "dis_reas", name: "Bunk Bed", price: 100 },
  { id: "h07", cat: "dis_reas", name: "Loft Bed", price: 100 },
  { id: "h08", cat: "dis_reas", name: "Storage Bed", price: 100 },
  { id: "h09", cat: "dis_reas", name: "Adjustable Bed", price: 100 },
  { id: "h10", cat: "dis_reas", name: "Desk L-shape", price: 75 },
  { id: "h11", cat: "dis_reas", name: "TV Stand", price: 75 },
  { id: "h12", cat: "dis_reas", name: "Desk Large", price: 75 },
  { id: "h13", cat: "dis_reas", name: "Entertainment Center / Wall Unit", price: 150 },
  { id: "h14", cat: "dis_reas", name: "China Cabinet 3+ piece (glass)", price: 400 },
  { id: "h15", cat: "dis_reas", name: "Pool Table", price: 800 },
  { id: "h16", cat: "cardboard", name: "Dining Table 4-seat (glass/marble)", price: 50 },
  { id: "h17", cat: "cardboard", name: "Dining Table 6+ seat (glass/marble)", price: 100 },
  { id: "h18", cat: "cardboard", name: "Coffee Table (glass/marble)", price: 50 },
  { id: "h19", cat: "cardboard", name: "Desk Top (glass/marble)", price: 50 },
  { id: "h22", cat: "cardboard", name: "Mirror XL (6ft+)", price: 50 },
  { id: "h23", cat: "cardboard", name: "Picture Frame XL (6ft+)", price: 50 },
  { id: "h24", cat: "cardboard", name: "Armoire 1-door w/ glass", price: 50 },
  { id: "h25", cat: "cardboard", name: "Curio / China Cabinet (glass)", price: 100 },
  { id: "h26", cat: "cardboard", name: "Dresser (fully mirrored)", price: 50 },
  { id: "h29", cat: "floor", name: "Masonite — install only", price: 75 },
  { id: "h30", cat: "floor", name: "Masonite — supply + install", price: 150 },
  { id: "h32", cat: "special", name: "Sofa Recliner (3-seat)", price: 50 },
  { id: "h33", cat: "special", name: "Sofa Bed (3-seat)", price: 50 },
  { id: "h34", cat: "special", name: "Piano — Upright", price: 200 },
  { id: "h35", cat: "special", name: "Piano — Baby Grand", price: 300 },
  { id: "h36", cat: "special", name: "Piano — Grand", price: 500 },
  { id: "h37", cat: "special", name: "Wine Fridge (3ft+)", price: 50 },
  { id: "h38", cat: "special", name: "Washer", price: 75 },
  { id: "h39", cat: "special", name: "Dryer", price: 75 },
  { id: "h40", cat: "special", name: "Stove", price: 75 },
  { id: "h41", cat: "special", name: "Refrigerator — Upright", price: 50 },
  { id: "h42", cat: "special", name: "Refrigerator — French door", price: 100 },
  { id: "h43", cat: "special", name: "Peloton Bike", price: 50 },
  { id: "h44", cat: "special", name: "Exercise Bike", price: 50 },
  { id: "h45", cat: "special", name: "Treadmill", price: 100 },
  { id: "h46", cat: "special", name: "Elliptical Machine", price: 100 },
  { id: "h48", cat: "special", name: "Grandfather Clock", price: 100 },
  { id: "h55", cat: "lta", name: "LTA — Last Time Adjustment", price: 0, editable: true },
];

export const HANDLING_CATS = {
  dis_reas: { label: "Disassembly / Reassembly", icon: "🔧" },
  cardboard: { label: "Cardboard Protection", icon: "📦" },
  floor: { label: "Floor Protection", icon: "🪵" },
  special: { label: "Special Items", icon: "⭐" },
  lta: { label: "Last Time Adjustment", icon: "💰" },
} as const;
